[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.16"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "e69720d204a4aa3b0c65dc91208645ba0a52b9cd"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"
